
skill-select:
  default: 8
  players-choose: true
# how big the pause ratio is between big and small pauses
pause-ratio: 1.75
# how long until your last click is expired in milliseconds
expire-ms: 10000


