
skill-select:
  # 0 LEFT_RIGHT_CLICK : 8 max skills - Sneaking while using left/right click *Note: only works with java
  # 1 CROUCH_CLICK : 1 max skill - Clicking while sneaking
  # 2 JUMP_CLICK : 1 max skill - Clicking while in the air
  # 3 CROUCH_JUMP_CLICK : 2 max skills - Clicking while sneaking or jumping
  # 4 TIMED_CLICK : 7 max skills - four timed clicks while sneaking with either big or small spaces between clicks (like reverse morse code) *Note: steep learning curve
  # 5 DOUBLE_CLICK : 1 max skill - two clicks less than {expire-ms} apart
  # 6 TRIPLE_CLICK : 1 max skill - three clicks less than {expire-ms} apart
  # 7 MULTI_CLICK : 3 max skills - double, triple, or quadruple click before {multi-click-trigger} ms have passed since the first click
  # 8 DIRECTIONAL_CLICK : 4 max skills - two clicks in different positions, the second click can be up/down/right/left to select a skill slot (IMO this is the easiest)
  default: 8
  # Players can choose their skill select type with /skill select (type)
  # Requires permission: notskills.sst - given by default
  players-choose: true
# maximum amount of skills an item can have
# any skills past 8 will not be able to be triggered
# this will override the notskills.max.<x>
max-skills: 8
# how big the pause ratio is between big and small pauses for TIMED_CLICK
pause-ratio: 1.75
# how long until your last click is expired in milliseconds
expire-ms: 10000
# how big the space in milliseconds between the first and last clicks in MULTI_CLICK to trigger
multi-click-trigger: 500
# display a redstone particle in front of the player when they select are selecting a skill
particles: true
# unlock skills when you hold items with a skill in your hand
natural-skill-unlock: true
# what rate a mythic mob will have to spawn with a skill item
mythic-mobs-skill-chance: 0.5

skills:
  1:
    # what the skill is called on skill artifacts and in item lore
    name: '&f&lLevitate'
    # Lore of skill item in skill select menu
    description:
      - ''
      - '&7Concentrate hard enough'
      - '&7to glide with the wind'
      - ''
    # how long in seconds before the player can use this skill again
    cooldown: 2.5
    # Starting the action with:
    # • [player] will run a command as the player
    # • [console] will run a command as the console
    # • [message] will send the player a message
    # • [mythicmobs] <mob> (optional:{target<x>}) will spawn mythic mob
    # • [mythicskills] <skillname> will use a Mythic Mobs skill
    # These characters will be replaced:
    # • {player} will be replaced with the player's name
    # • {world} will be replaced with the world name
    # • {dimension} will be replaced with the dimension name
    # • {target<x>} will be replaced with the block position that the player is looking at with a maximum distance of x
    # • {random<x>} will be replaced with a random number from 0 (inclusive) to x (non-inclusive)
    # • {random<y>_<x>} will be replaced with a random number from y (inclusive) to x (non-inclusive)
    # External plugin support:
    # • Placeholders will be parsed as the player
    # • Mythic Mobs can be spawned by skills and use skills. You can also use the Mythic Mob skills as a skill action
    actions:
      - '[console] execute run effect give {player} levitation {random1_5} 1 false'
      - '[message] &7&oYou appear to feel lighter.'
      #- '[mythicmobs] SkeletalKnight' # will spawn a Skeletal Knight if mythic mobs is enabled
      #- '[mythicskills] WitheringBladeStrike'
    # Which items the skill can be applied to (using the command to add skills bypasses this)
    # • The name of the item material must include at least one string in the list
    # • Add "*" at the beginning to match the string strictly
    # • Leave the list empty to allow the skill on all items
    # In this case, a stick, all types of hoes, and a blaze rod can have this skill be attached to them
    allowed-items:
      - '*Stick'
      - 'Hoe'
      - 'Blaze_Rod'
      - 'Iron_Sword'
    mythic-mobs:
      weight: 1 # how likely a mob will spawn with this specific skill
       # what mobs can spawn with this skill - leave empty to allow all mythic mobs
      included-mobs:
        - 'SkeletalKnight'
  2:
    name: '&f&lSmite'
    description:
      - ''
      - '&7The gods act in your favor'
      - ''
    cooldown: 5
    actions:
      - '[console] execute positioned {target20} run summon minecraft:lightning_bolt'
    allowed-items: []
  3:
    name: '&f&lSeed Prank'
    description:
      - ''
      - '&7First day on the job?'
      - ''
    cooldown: 360
    actions:
      - '[message] &7&oWhere did these seeds come from?'
      - '[console] give {player} wheat_seeds 3600'
    allowed-items: []
  4:
    name: '&f&lLuck Reading'
    description:
      - ''
      - '&7Say you''re addicted to gambling'
      - '&7without saying you''re addicted'
      - '&7to gambling'
      - ''
    cooldown: 1200
    actions:
      - '[message] &eYour daily luck reading (0-10) is...'
      - '[message] &d&l{random10}'
    allowed-items: []


