name: NotSkills
version: '${project.version}'
main: me.jadenp.notskills.NotSkills
api-version: 1.19
softdepend:
  - PlaceholderAPI
  - MythicMobs
  - MultiVerse-Core
  - Magic
commands:
  notskills:
    description: Use this plugin!
    aliases: [ns, skill]
permissions:
  notskills.admin:
    description: Use the admin commands!
    default: op
  notskills.sst:
    description: set your skill select type
    default: true
