# -1 to let the players choose
skill-select-type: 0
# how big the pause ratio is between big and small pauses
pause-ratio: 1.75
# how long until your last click is expired in milliseconds
expire-ms: 10000


